sudo: true
dist: bionic

language: python
python:
  - "3.4"

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./functional_tests/biodaniel-test.sh -p biodaniel -d functional_tests/test_data
  - ./.travis/unit-test.sh
  - coverage combine .coverage functional_tests/test_data/.coverage
  - codecov

